title: Terry Tu
email: terry20021026@gmail.com
description: >-
  This is Terry's first personal website.
baseurl: ""
url: "https://tejmaster.github.io"
github_username: TEJMaster
theme: jekyll-theme-cayman
